const express = require('express')
const router = express.Router()
const {createPost, displayPost,likeSystemIncrease, likeSystemDecrease, singlePost, createComment, createReply, displayPostForProfile , deletePost, editPost} = require('../controllers/ิpostController')
const {createAccount,loginAccount, accountData, logoutAccount, singleAccountData, getAllAccounts , verifyOTPAccount , sendOTPAccount , addProfileImage , TokenAuthenticaiton} = require('../controllers/userController')
const { makingRequest, requestCheck, requestCheck1, removeRequest, acceptRequest, fetchFriendRequest, fetchFriendlist } = require('../controllers/friendController')
const { createChatroom, sendMessage, getMessage, readMessage, getAllMessages,  getAllMessageAndAccounts, deleteChatmessegeRoom } = require('../controllers/chatController')
const { createTalkingRoom, getTalkingRooms, getSingleTalkingRoom, getAllMembers, requestToTheRoom, getRoomRequest, deleteRoomRequest, allRoomRequested, acceptRoomRequested, rejectRoomRequested, createChatroomInTalkingroom , createTalkingroomInTalkingroom, chatroomDataUpdated , chatroomDataDeleted, changeRoomInfo, getOutOfTheRoom , getOutOfTheRoomAdmin , roomDeleting , levelUpToAdmin , levelDownToParticipant , messagesFromChatroomInRoom , memberGetInTalkingroom, memberGetOutOfTalkingroom, onlineToTheRoomAdmin, onlineToTheRoomParticipant, offlineFromTheRoomAdmin, offlineFromTheRoomParticipant , talkingChannelDataUpdated, talkingChannelDataDeleted , onlineToTheRoomCreator , offlineFromTheRoomCreator} = require('../controllers/roomController')


//post
router.post('/create-post',TokenAuthenticaiton,createPost) 
router.get('/display-post',TokenAuthenticaiton,displayPost)
router.put('/like-increasing',TokenAuthenticaiton,likeSystemIncrease)
router.delete('/like-decreasing',TokenAuthenticaiton,likeSystemDecrease)
router.get('/single-post/:id',TokenAuthenticaiton,singlePost)
router.get('/display-post-profile/:id',TokenAuthenticaiton,displayPostForProfile)
router.post('/create-comment',TokenAuthenticaiton,createComment)
router.post('/create-reply',TokenAuthenticaiton,createReply)
router.delete('/delete-post',TokenAuthenticaiton,deletePost)
router.put('/edit-post',TokenAuthenticaiton,editPost)
//account
router.post('/create-account',createAccount)
router.put('/verify-otp-account',verifyOTPAccount)
router.post('/send-otp-account',sendOTPAccount)
router.put('/add-profile-image',addProfileImage)
router.post('/login-account',loginAccount)

router.get('/account-data',accountData)
router.post('/logout-account',TokenAuthenticaiton,logoutAccount)
router.get('/single-account-data/:id',TokenAuthenticaiton,singleAccountData)
router.get('/get-all-accounts',TokenAuthenticaiton,getAllAccounts)

//friends
router.post('/making-request',TokenAuthenticaiton,makingRequest)
router.post('/checking-request',TokenAuthenticaiton,requestCheck)
router.delete('/remove-request',TokenAuthenticaiton,removeRequest)
router.put('/accept-request',TokenAuthenticaiton,acceptRequest)
router.get('/all-friendRequest/:accountID',TokenAuthenticaiton,fetchFriendRequest)
router.get('/all-friends-get/:accountID',TokenAuthenticaiton,fetchFriendlist)


//Chatrooms
router.post('/create-chatmessege-room',TokenAuthenticaiton,createChatroom)
router.put('/send-message',TokenAuthenticaiton,sendMessage)
router.post('/get-message',TokenAuthenticaiton,getMessage)
router.post('/read-message',TokenAuthenticaiton,readMessage)
router.get('/all-messages/:senderID',TokenAuthenticaiton,getAllMessages)
router.post('/all-messages-accounts',TokenAuthenticaiton,getAllMessageAndAccounts)

//Talkingrooms
router.post('/create-talkingroom',TokenAuthenticaiton,createTalkingRoom)
router.post('/all-talkingrooms',TokenAuthenticaiton,getTalkingRooms)
router.post('/get-single-talkingroom',TokenAuthenticaiton,getSingleTalkingRoom)
router.post('/get-all-members',TokenAuthenticaiton,getAllMembers)
router.put('/room-request',TokenAuthenticaiton,requestToTheRoom)
router.get('/get-room-request/:accountID',TokenAuthenticaiton,getRoomRequest)
router.delete('/delete-room-request',TokenAuthenticaiton,deleteRoomRequest)
router.get('/all-room-requested/:adminID',TokenAuthenticaiton,allRoomRequested)
router.put('/accept-room-requested',TokenAuthenticaiton,acceptRoomRequested)
router.delete('/reject-room-requested',rejectRoomRequested)
router.post('/create-chatroom-in-talkingroom',TokenAuthenticaiton,createChatroomInTalkingroom)
router.post('/create-talkingroom-in-talkingroom',TokenAuthenticaiton,createTalkingroomInTalkingroom)
router.put('/chatroom-data-updated',TokenAuthenticaiton,chatroomDataUpdated)
router.delete('/chatroom-data-deleted',TokenAuthenticaiton,chatroomDataDeleted)
router.put('/change-room-info',TokenAuthenticaiton,changeRoomInfo)
router.delete('/get-out-of-the-room',TokenAuthenticaiton,getOutOfTheRoom)
router.delete('/get-out-of-the-room-admin',TokenAuthenticaiton,getOutOfTheRoomAdmin)
router.delete('/room-deleting',TokenAuthenticaiton,roomDeleting)
router.put('/level-up-to-admin',TokenAuthenticaiton,levelUpToAdmin)
router.put('/level-down-to-participant',TokenAuthenticaiton,levelDownToParticipant)
router.post('/messages-from-chatroom-in-room-sending',TokenAuthenticaiton,messagesFromChatroomInRoom)
router.delete('/delete-chatmessege-room',TokenAuthenticaiton,deleteChatmessegeRoom)
router.put('/member-get-in-talkingroom',TokenAuthenticaiton,memberGetInTalkingroom)
router.put('/member-get-out-of-talkingroom',TokenAuthenticaiton,memberGetOutOfTalkingroom)
router.put('/online-to-the-room-admin',TokenAuthenticaiton,onlineToTheRoomAdmin)
router.put('/online-to-the-room-participant',TokenAuthenticaiton,onlineToTheRoomParticipant)
router.put('/online-to-the-room-creator',TokenAuthenticaiton,onlineToTheRoomCreator)
router.put('/offline-from-the-room-admin',TokenAuthenticaiton,offlineFromTheRoomAdmin)
router.put('/offline-from-the-room-participant',TokenAuthenticaiton,offlineFromTheRoomParticipant)
router.put('/offline-from-the-room-creator',TokenAuthenticaiton,offlineFromTheRoomCreator)
router.put('/talkingChannel-data-updated',TokenAuthenticaiton,talkingChannelDataUpdated)
router.delete('/talkingChannel-data-deleted',TokenAuthenticaiton,talkingChannelDataDeleted)

module.exports = router